katalog/urls.py
# Implement Routings 

from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import create_task_ajax, show_json, show_todolist, register, login_user, logout_user, create_task, delete_task, update_task

app_name = "todolist"

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create-task'),
    path('delete/<int:pk>', delete_task, name='delete_task'),
    path('update/<int:pk>', update_task, name='update_task'),
    path('json/', show_json, name='show_json'),
    path('add/', create_task_ajax, name='create_task_ajax'),
]

todolist/models.py
from datetime import datetime
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class ToDoList(models.Model):
    user = models.ForeignKey(
           User, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    status = models.BooleanField(default=False)

todolist/forms.py
from django.forms import ModelForm
from todolist.models import ToDoList

class ToDoListForm(ModelForm):
    class Meta:
        model = ToDoList
        fields = ["title", "description"]

todolist/views.py
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect, get_object_or_404
from todolist.models import ToDoList
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.core import serializers
from django.urls import reverse
import datetime

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    todolist_data = ToDoList.objects.filter(user=request.user)

    context = {
        "list_of_todos" : todolist_data,
        "username": request.user.username,
    }
    return render(request, 'todolist.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) 
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

# Code reference: https://docs.djangoproject.com/en/4.1/topics/forms/
@login_required(login_url='/todolist/login/')
@csrf_exempt
def create_task(request):
    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get('description')
        user = request.user

        ToDoList.objects.create(user=user, title=title, description=description)        
        return HttpResponseRedirect('/todolist/')
    
    return render(request, 'create-task.html', {})

@login_required(login_url='/todolist/login/')
@csrf_exempt
def create_task_ajax(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        user = request.user

        ToDoList.objects.create(user=user, title=title, description=description)
        return JsonResponse({'error': False})

@login_required(login_url='/todolist/login/')
@csrf_exempt
def update_task(request, pk):
    task_update = ToDoList.objects.get(user=request.user, pk=pk)
    task_update.status = not (task_update.status)
    task_update.save()
    return HttpResponseRedirect(reverse('todolist:show_todolist'))

@login_required(login_url='/todolist/login/')
@csrf_exempt
def delete_task(request, pk):
    ToDoList.objects.get(user=request.user,pk=pk).delete()
    return HttpResponseRedirect(reverse('todolist:show_todolist'))

@login_required(login_url='/todolist/login/')
def show_json(request):
    data = ToDoList.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', data), content_type='application/json')

todolist/templates/create-task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}  

<style>
    * {
        font-family: Arial;
        vertical-align: top;
        text-align: left;
    }
    h1, h2 {
        color: black;
    }
    th, td {
        font-size: 120%;
        padding: 12px 15px
    }
    table{
        border-collapse: collapse;
        margin: 30px auto;
        font-size: 0.9em;
        font-family: sans-serif;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
        border-radius: 6px;
    }
    .padding {
        padding-top: 30px;
    }
    .button {
        border: none;
        color: white;
        font-weight: bold;
        background-color: #6200EE;
        text-decoration: none;
        padding: 5px 20px;
        font-size: 16px;
        cursor: pointer;
        border-radius: 6px;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 10px 15px 0 rgba(0,0,0,0.19);
    }
</style>

<!-- Code taken from register.html with a few alterations -->
<div class="padding">
    <h1 style="text-align: center; font-weight: bold;">Create New Task</h1>   
        <form method="POST">  
            {% csrf_token %}
            <table>  
                {{ form.as_table }}
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Add" class="button"/></td>  
                </tr> 
            </table>
        </form>
</div>  

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<style>
    * {
        font-family: Arial;
        text-align: center;
        vertical-align: middle;
    }
    h1, h2 {
        color: black;
    }
    th, td {
        font-size: 120%;
        padding: 12px 15px
    }
    table{
        border-collapse: collapse;
        margin: 30px auto;
        font-size: 0.9em;
        font-family: sans-serif;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
        border-radius: 6px;
    }
    .padding {
        padding-top: 30px;
    }
    .button {
        border: none;
        color: white;
        font-weight: bold;
        background-color: #6200EE;
        text-decoration: none;
        padding: 5px 20px;
        font-size: 16px;
        cursor: pointer;
        border-radius: 6px;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 10px 15px 0 rgba(0,0,0,0.19);
    }
</style>
<div class="padding">
    <div class = "login">

        <h1 style="font-weight: bold;">Login</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="button login_btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <td>
                {% for message in messages %}
                    <td>{{ message }}</td>
                {% endfor %}
            </td>
        {% endif %}     
            
        <br><br>
        Don't have an account?  <a href="{% url 'todolist:register' %}">Register now!</a>

    </div>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<style>
    * {
        font-family: Arial;
        text-align: left;
        vertical-align: top;
    }
    h1, h2 {
        color: black;
    }
    th, td {
        font-size: 120%;
        padding: 12px 15px
    }
    table{
        border-collapse: collapse;
        margin: 30px auto;
        font-size: 0.9em;
        font-family: sans-serif;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
        border-radius: 6px;
    }
    .padding {
        padding-top: 30px;
        padding-left: 8px;
        padding-right: 8px;
    }
    .button {
        border: none;
        color: white;
        font-weight: bold;
        background-color: #6200EE;
        text-decoration: none;
        padding: 5px 20px;
        font-size: 16px;
        cursor: pointer;
        border-radius: 6px;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 10px 15px 0 rgba(0,0,0,0.19);
    }
</style>

<div class="padding">
    <div class = "login">
    
        <h1 style="text-align: center; font-weight: bold;">Create New Account</h1>  
    
            <form method="POST">  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input type="submit" name="submit" value="Register" class="button"/></td>  
                    </tr>  
                </table>  
            </form>
    
        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}
    </div>  
</div>


{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>{{username}}'s To Do List</title>
{% endblock meta %}

{% block content %}
<!doctype html>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<head>
    <style>
        * {
            font-family: 'Arial';
            text-align: center;
            vertical-align: middle;
        }
        .text-style {
            font-weight: bold;
        }
        th, td {
            font-size: 120%;
            padding: 12px 15px
        }
        table{
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            font-size: 0.9em;
            font-family: sans-serif;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
            border-radius: 6px;
        }
        .button {
            border: none;
            color: white;
            font-weight: bold;
            text-decoration: none;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            border-radius: 6px;
            box-shadow: 0 2px 6px 0 rgba(0,0,0,0.2), 0 8px 13px 0 rgba(0,0,0,0.19);
        }
        a:hover{
            color:white;
        }
        .padding {
            padding-top: 30px;
            padding-left: 60px;
            padding-right: 60px;
            padding-bottom: 80px;
        }
        .wrap {
            display: flex;
            align-items: center;
            align-content: flex-start;
            justify-content: space-between;
        }
        #rcorners1 {
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
            border-radius: 25px;
            padding-top: 40px;
            padding-left: 40px;
            padding-right: 40px;
            width: 100%;
        }
        .card{
            border-radius: 4px;
            background: #fff;
            box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05);
            transition: .3s transform cubic-bezier(.155,1.105,.295,1.12),.3s box-shadow,.3s -webkit-transform cubic-bezier(.155,1.105,.295,1.12);
        }

        .card:hover{
            transform: scale(1.05);
            box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
            background: linear-gradient(
            45deg,
            rgba(29, 236, 197, 0.5),
            rgba(91, 14, 214, 0.5) 100%)
        }
    </style>
</head>

<body class="padding">
    <h1 class="text-style" style="margin-bottom: 50px; font-size: 50px;">Hello {{username}}!</h1>
    <div class="wrap" style="margin-bottom: 40px;">
        <h2 class="text-style" style="font-size: 30px;"> This to Your To Do List!</h2>
        <button type="button" class="button_select_new button_select button" data-bs-toggle="modal" data-bs-target="#addModal" style="background-color:#6200EE">Create new task</button>
    </div>

    <!-- Modal from: https://getbootstrap.com/docs/5.2/components/modal/ -->
    <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="addModalLabel" style="font-weight: bold;">Create a new task</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body justify-content-center" style="display:block; margin:0 auto">
                    <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <input type="text" name="title" maxlength="255" placeholder="Task Name">
                    <br>
                    <input style="margin-top: 16px;" type="text" name="description" placeholder="Task Description">
                </div>
                <div class="modal-footer" style="justify-content: center;">
                    <button id="button" type="submit" class="button_select button_select_new button" data-bs-dismiss="modal" style="background-color:#6200EE">Create Task</button>
                </div>
            </div>
        </div>
    </div>

    <div class="row" id="cards"></div>

    <script>
        $(document).ready(function () {
            taskCards();
        });
        document.getElementById("button").onclick = addTodo

        $("#addModal").on("hidden.bs.modal", function (e) {
            $("#form").find("input[type=text]").val("");
        })

        // Source (Solusi Tutorial 5) 
        // https://github.com/pbp-fasilkom-ui/tutorial-5-example/blob/main/barang_wishlist/templates/index_wishlist.html
        function addTodo() {
            fetch("/todolist/add/", {
            method: "POST",
            body: new FormData(document.querySelector("#form"))
            }).then(taskCards)
            return false
        }

        
        function taskCards() {
            let stringHTML = "";
            $.ajax({
                url: "json",
                type: "GET",
                dataType: "json",
                success: function(data) {
                    for (i=0; i<data.length; i++){
                        let status = data[i].fields.status ? "Done" : "Not Started";
                        stringHTML += `
                        <div class="col-md-6 col-lg-3">
                            <div class="card shadow p-3 mb-5 bg-white rounded border-0" style="padding-right: 10px;">
                                <div class="card-body d-flex flex-column">
                                    <h4 class="card-title" style="font-weight: bold; color: #6638A6;">${data[i].fields.title}</h4>
                                    <h5 class="card-text">${status}</h5>
                                    <p class="card-text" style="font-size: 16px;">${data[i].fields.date}</p>
                                    <p class="card-text">${data[i].fields.description}</p>
                                    <div class="mt-auto">
                                        <a href="update/${data[i].pk}", class="button" style="background-color: #01C89A">Update</a>
                                        <a href="delete/${data[i].pk}", class="button" style="background-color: #FF642F">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>`;
                        $('#cards').html(stringHTML);
                    }
                }
            });
        }
    </script>
    
    <a href="{% url 'todolist:logout' %}" class="button" style="float: right; background-color: #6200EE">Logout</a>
    
</body>
</html>

{% endblock content %}